### PR TITLE
EpochMonitor callback for monitoring progress within epochs

### PR DESCRIPTION
**Pull request by AdamStone**
When using a large training set, it can take a long time for the first epoch to complete and display the first monitor update. I wanted to see that progress was being made during the epoch, so I wrote an SGD callback to do this using the method suggested by Ian here https://groups.google.com/forum/#!topic/pylearn-users/Mz1_1yqSYeA

This can be used to print simple one-line updates giving the current epoch and batch at a specified rate, and/or to print monitor updates within epochs at a specified rate. 

I also made the file consistent with PEP8.

### CODE REVIEW

**Comment by dwf** [comment]
Could you rebase the commits you've added against current master? That would make it easier to review this. But it sounds really useful, so thank you in advance.

**Comment by AdamStone** [comment]
Sure, I suppose it's about time I figure out how rebasing works anyway

**Comment by AdamStone** [comment]
I think I did it right, if not let me know.

**Comment by lamblin** [comment]
It looks good, thanks!
Now that you have fixed all sort of pep8 violations in that file, could you take it off the pep8 whitelist in https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/devtools/tests/test_format.py#L145 ?
Also, don't worry about it now, but for the future, if you can separate commits that do only reformatting from commits that change the code itself, it can make things easier to review.
@dwf, do you want to take another look?

**Comment by AdamStone** [comment]
Sure, that sounds like a good idea. I was originally just intending to add the EpochMonitor code, and I fixed the PEP8 without really thinking about it in order to pass the automated tests.

**Comment by AdamStone** [comment]
Hmm.. Somehow the build is now failing, with PEP8 problems that apparently aren't recognized by my check PEP8 script. I can fix them, but I wonder why it passed the tests before.

**Comment by lamblin** [comment]
Sorry for the reviewing delay.
Do you think you could add a small test, based on your YAML example, so that this feature does not break in the future? In particular, you could check that the right number of values are in the monitoring channels.
You can use the classes (datasets, and so on) defined in `pylearn2/testing` for dummy objects.
@dwf did you have other comments?

**Comment by AdamStone** [comment]
Sure, I'll give it a try.

**Comment by AdamStone** [comment]
It seems I'm failing my own test in the build check, but I'm not seeing why. If I run the test myself, there's no assertion error. Maybe I'm missing something about how the testing is supposed to work?

**Comment by lamblin** [comment]
The buildbot launches the tests in different settings, including with "floatX=float32" in the theano flags, and using python 3.
My guess is that `n_batches/monitor_rate` is interpreted as floating point division on python 3, and integer division in python 2, so they could give different results. `n_batches // monitor_rate` should be integer division for both.

**Comment by AdamStone** [comment]
Ah yes, that would explain the discrepancy. I didn't see 'from __future__ import division', so I thought I was safe.

**Comment by AdamStone** [comment]
Test passing now.

**Pull request merged**
