### PR TITLE
Added unit tests for rotated mnist and adult

### PR DESCRIPTION
**Pull request by kelvinxu**
Added two tests based on previous pull request #666 

Kelvin

### CODE REVIEW

**Comment by kelvinxu** [comment]
added docstrings/ checked files with pyflakes

**Comment by memimo** [comment]
Travis is failing still because multiple docstring errors

**Comment by kelvinxu** [comment]
I'll fix.

**Comment by memimo** [comment]
Ideally we need more through tests epescially for mnist. But since it's been used less we can go as it is for now.
One more comment is, if you're fixing minor issues you can avoid making new commits by using git --amend.
Would you mind cleaning your commit history with git rebase. Git commits should be divided based on the logic not the author's work progress. You need to force push after you clean the history, then it should be ready for merge.

**Comment by kelvinxu** [comment]
Thanks for the comments, I'll keep that in mind in the future. I squashed a bunch of the commits that were just docstrings/pep8.

**Comment by memimo** [comment]
Thx!

**Pull request merged**
