### PR TITLE
EpochCounter bugfix, fix for #1078

### PR DESCRIPTION
**Pull request by hantek**

### CODE REVIEW

**Comment by memimo** [comment]
don't forget the term fixes #1078 inside the comment or description for cross reference.

**Comment by hantek** [comment]
Hi, Mehdi, I added a reference at #1078

**Comment by hantek** [comment]
Hi Mehdi, 

I fixed the PEP8 respect, but travis is complaining about "KeyError: "'train_y_roc_auc"...
That is a channel name in monitor, and used only in the test file pylearn2/train_extensions/tests/test_roc_auc.py

What is that? I can't figure out how my modification in other files end up with changing the channel name for this test.

**Comment by lamblin** [comment]
Superseeded by #1480.

**Pull request closed without merging**
