### PR TITLE
Ignore false positive for GPU_mrg_uniform in nan_guard - fixes #1465

### LINKED ISSUE #1465: NanGuardMode false positive in GPU_mrg_uniform
This resulted from the discussion on [pylearn-users](https://groups.google.com/forum/#!topic/pylearn-users/4E7xYRCJ-7I) mailing list.

Long story short [NanGuardMode](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/devtools/nan_guard.py) detects Nans with every invocation of GPU_mrg_uniform.

@lamblin provided following insight:
> In more detail, GPU_mrg_uniform actually has an input, which is a shared variable containing the current state of the random number generator. When computing a new sample, the Op actually generates two outputs: a new value for the state, and the sample itself. There is a mechanism to automatically update the value of the shared state to the new expression every time a function using it is called. 
> 
> For MRG, the random state is a matrix of int32. However, when using the GPU, we want the state to be kept and updated in GPU memory for speed, but the current GPU back-end of Theano only supports float32 containers. Therefore, Theano cheats by masquerading a matrix of int32 as a matrix of float32, and the random generator itself knows that it should interpret them as int32. 
>
> The unfortunate side effect is that it looks like a matrix of float32, and that some legitimate values for int32 will have the same binary representation as a NaN in float32, which is probably what is going on in your case.

### PR DESCRIPTION
**Pull request by TNick**
I've also took the liberty to reformat the output a bit and to remove a todo.

### CODE REVIEW

**Comment by lamblin** [comment]
That's the right place to add the exclusion. However:
- I don't really like the idea of matching types by string.
- It is not all inputs and outputs that should be ignored, just the random states.
I think it may be better to either add a note in the variables' tag, for instance `state.tag.ignore_nan`, when it is built, and then have `NanGuardMode` check that tag.

**Comment by TNick** [comment]
That's a beautiful solution. However, `GPU_mrg_uniform` is not referenced anywhere in pylearn2.
So, you're saying that changes should be made to Theano source, which I'm uncomfortable with doing myself.
Also, based on your comments, the syntax should allow filtering inputs/outputs, not nodes (like in the case of `NanGuardMode` that will  only check generated array and will skip the state.

Bottom line, I believe that some solution should be implemented, as my understanding is that `NanGuardMode` is unusable right now. Am I the only one to use it? Shouldn't be hordes of users complaining?

**Comment by lamblin** [comment]
Yes, I think that the real solution will need a change in Theano, but `NanGuardMode` is in the process of being moved to Theano (see issue #1172), so it does not bother me particularly.
`NanGuardMode` is functional if you do not draw your random numbers on GPU. Since `NanGuardMode` is extremely slow when using the GPU currently (every intermediate result gets transferred to the CPU memory twice), disabling the GPU would be a good idea anyway.

**Comment by lamblin** [comment]
I opened https://github.com/Theano/Theano/issues/2826 as a Theano ticket to take care of it once #1172 is finished.

**Pull request closed without merging**
