### PR TITLE
Add 'channels' option to enable non-interactive plotting

### PR DESCRIPTION
**Pull request by johnarevalo**
Include option to generate monitoring plots in a non-interactive environment like a bash script or ssh remote executions.

### CODE REVIEW

**Comment by dwf** [comment]
This needs a rebase but LGTM otherwise.

**Comment by lamblin** [comment]
Rebase has been done.
@johnarevalo The maintainers are not automatically notified when new commits are pushed, but they are if a new comment is submitted. Don't hesitate to add a comment when you update a PR.

**Comment by johnarevalo** [comment]
@lamblin Thanks for your advice. I hope to do so in future PRs.

**Comment by nouiz** [comment]
Note, we don't support Pylearn2 anymore and we are dropping Theano: 

https://groups.google.com/forum/#!topic/theano-users/7Poq8BZutbY

So I just want to war people that probably nobody will review this PR.

**Pull request closed without merging**
