### PR TITLE
bugfix for fprop_step definition in masked LSTM

### PR DESCRIPTION
**Pull request by mkraemer67**

### CODE REVIEW

**Comment by dwf** [comment]
@bartvm I think you'd be most qualified to review this?

**Comment by bartvm** [comment]
I can have a look, but the `fprop_step` is @jych's code which I'm less familiar with, so maybe @jych can have a quick look as well

**Comment by bartvm** [comment]
Indeed looks like a bug to me, so happy to accept the bug fix. Will merge in a bit if I don't hear from @jych

**Comment by jych** [comment]
I actually have a pull request to fix this issue.
This was what I've told three weeks ago.
https://github.com/lisa-lab/pylearn2/pull/1320

**Comment by bartvm** [comment]
Oops, completely forgot about that PR over Christmas. Apologies! I've just merged it, which should make this PR redundant. Thanks either way @mkraemer67!

**Comment by jych** [comment]
Cool. Thanks @mkraemer67 :)

**Comment by mkraemer67** [comment]
Sure, glad to be of help. Thanks for the PR @jych.

**Pull request closed without merging**
