### PR TITLE
fixing bug with creating masks

### PR DESCRIPTION
**Pull request by aalmah**
creating masks was done after swapping axes, which gave wrong masks

### CODE REVIEW

**Comment by lamblin** [comment]
Something went wrong in the rebasing.
Do you need help with that?

**Comment by lamblin** [comment]
OK, the rebase did work. There is a pep8-related error:
```
/home/travis/build/lisa-lab/pylearn2/pylearn2/sandbox/rnn/space/__init__.py:269:1: W293 blank line contains whitespace

/home/travis/build/lisa-lab/pylearn2/pylearn2/sandbox/rnn/space/__init__.py:281:80: E501 line too long (83 > 79 characters)

/home/travis/build/lisa-lab/pylearn2/pylearn2/sandbox/rnn/space/__init__.py:283:16: E231 missing whitespace after ','

/home/travis/build/lisa-lab/pylearn2/pylearn2/sandbox/rnn/space/__init__.py:284:16: E231 missing whitespace after ','
```
@bartvm can you have a look?

**Comment by bartvm** [comment]
LGTM, about time this bug was fixed! I think most people fixed it locally, but it's a really major bug that really should be fixed in the repo.

**Comment by lamblin** [comment]
Good!
@aalmah I'll let you fix the pep8 thing, and then we are good to merge.

**Pull request merged**
