### PR TITLE
Added test for ZCA_Dataset.

### LINKED ISSUE #899: Add unit tests for ZCA_Dataset
People keep breaking this. Every time I try to use it it's broken in a new way.

### PR DESCRIPTION
**Pull request by Thrandis**
Fixes #899

### CODE REVIEW

**Comment by Thrandis** [comment]
Well it was always failing otherwise.
I ran some tests using between 10 and 1000 examples, and the variance gets never close to 1, but rather around 0.9. Maybe am I using too few examples?

**Comment by Thrandis** [comment]
Well it was always failing otherwise.
I ran some tests using between 10 and 1000 examples, and the variance gets never close to 1, but rather around 0.9. Maybe am I using too few examples?

**Comment by dwf** [comment]
Perhaps try with `filter_bias=0` and see if that fixes it.

**Comment by Thrandis** [comment]
Yep it works! The tolerance can be pushed to 0.01. Is it precise enough?

**Comment by dwf** [comment]
Sounds good to me.

**Comment by memimo** [comment]
Sorry for late review. LGTM too. I am merging.
@Thrandis for future for unit tests that needs some preparation you can use python's unit test class and divide each test in different class method.

**Pull request merged**
