### PR TITLE
Upgraded weight initialization to include initializing by sampling a …

### PR DESCRIPTION
**Pull request by daemonmaker**
…Gaussian.

@lamblin I tried to make this backwards compatible however it's not 100% so because I added a parameter in the middle of some of the parameter lists. I can move that to the end if that's preferable.

### CODE REVIEW

**Comment by daemonmaker** [comment]
@lamblin Travis is failing but the error doesn't appear to be related to my changes. Would you please look at the error and let me know whether it is something I need to chase done to get this merged?

**Comment by daemonmaker** [comment]
@lamblin It appears Travis is passing now though I didn't change anything. Can this be merged?

**Comment by bartvm** [comment]
Te test that failed has some randomness in it, and you just got unlucky and fell right above the tolerance level, so restarting it solved the problem.

**Comment by lamblin** [comment]
@bartvm Do you remember which test that was?
@daemonmaker It looks fine, thanks!

**Comment by bartvm** [comment]
I'm quite sure it was `test_zca_dataset`, one of [these two lines](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/datasets/tests/test_zca_dataset.py#L35-L36) probably, because I can remember `atol` being set to something non-zero.

**Comment by lamblin** [comment]
@bartvm Thanks, I'll try to make the test deterministic again.

**Pull request merged**
